services:
  django:
    build: .
    command: sh -c "cd ./src &&
      python manage.py makemigrations && 
      python manage.py migrate && 
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - media:/usr/src/app/src/media
    depends_on:
      - db

  db:
    image: postgres:15
#    environment:
#      - POSTGRES_USER=main
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=main
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  media: